# Generated by Django 3.1.5 on 2021-01-25 09:57

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_name', models.CharField(max_length=200)),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('ktp_in_charge', models.CharField(blank=True, max_length=16, null=True)),
                ('telephone', models.CharField(blank=True, max_length=20, null=True)),
                ('handphone', models.CharField(blank=True, max_length=20, null=True)),
                ('type_organization', models.CharField(blank=True, choices=[('Masjid', 'Masjid / Mosque'), ('Orphanage', 'Panti Asuhan / Orphanage'), ('Human Social Welfare', 'Social Welfare'), ('Animal Social Welfare', 'Animal Social Welfare'), ('Educational Institution', 'Education Institution/Community'), ('People Community', 'People Community'), ('Religious Community', 'Religious Community'), ('Religious Organization', 'Religious Organization'), ('Sport Association', 'Sport Association'), ('Sport Community', 'Sport Community/Organization'), ('CSR', 'Community Social Responsibility'), ('Other', 'Other')], max_length=50, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('verified', 'verified'), ('unverified', 'unverified')], default='unverified', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DonorRecipient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ktp_id', models.CharField(blank=True, max_length=16, null=True)),
                ('kk_id', models.CharField(blank=True, max_length=16, null=True)),
                ('jobs', models.CharField(blank=True, max_length=20, null=True)),
                ('job_status', models.CharField(blank=True, choices=[('Unemployed', 'Unemployed / Belum Bekerja'), ('Jobless', 'Jobless / Pengangguran'), ('Labor Force', 'Labor Force / Buruh'), ('Pedagang Asong', 'Pedagang Asong'), ('Serabutan', 'Serabutan'), ('Farmer', 'Petani / Farmer'), ('Maid', 'ART / HouseMaid'), ('Marbot', 'Marbot'), ('Tukang Jahit', 'Tukang Jahit'), ('Cleaning Service', 'Cleaning Service'), ('Driver', 'Supir / Driver'), ('Sex Labour', 'Sex Labour / WTS / Pekerja Seks')], max_length=50, null=True)),
                ('marital_status', models.CharField(blank=True, choices=[('Single', 'Single / Bujang'), ('Divorce-1', 'Divorce / Duda / Janda / Cerai Hidup'), ('Divorce-2', 'Divorce / Duda / Janda / Cerai Mati'), ('Polygamous', 'Polyginy'), ('Castrate', 'Castrate')], max_length=50, null=True)),
                ('family_status', models.CharField(blank=True, max_length=20, null=True)),
                ('contact_number', models.CharField(blank=True, max_length=20, null=True)),
                ('keluarga_tanggungan', models.IntegerField()),
                ('birth_date', models.DateField()),
                ('pengeluaran_per_bulan', models.IntegerField()),
                ('status', models.CharField(choices=[('verified', 'verified'), ('unverified', 'unverified')], default='unverified', max_length=20)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_location', models.CharField(blank=True, max_length=100, null=True)),
                ('home_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('home_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('ktp_id', models.CharField(blank=True, max_length=16, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=16, null=True)),
                ('status', models.CharField(choices=[('verified', 'verified'), ('unverified', 'unverified')], default='unverified', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
